---
title: "Практическое задание №3"
author: "Журавлева Юлия БИСО-01-20"
format:   
  md:
    output-file: README.md
---

# Анализ данных сетевого трафика при помощи библиотеки Arrow

## Цель работы

1. Изучить возможности технологии Apache Arrow для обработки и анализ больших данных
2. Получить навыки применения Arrow совместно с языком программирования R
3. Получить навыки анализа метаинфомации о сетевом трафике
4. Получить навыки применения облачных технологий хранения, подготовки и анализа данных: Yandex Object Storage, Rstudio Server.

## Исходные данные

1. Ноутбук с ОС Windows 10
2. RStudio
3. Yandex Cloud
4. Библиотека Arrow
5. RStudio Server

## Задание

Используя язык программирования R, библиотеку arrow и облачную IDE Rstudio Server, развернутую в Yandex Cloud, выполнить задания и составить отчет.

## Ход работы

Импорт данных
Обработка данных

## Анализ

Задание 1: Найдите утечку данных из Вашей сети
Задание 2: Найдите утечку данных 2
Задание 3: Найдите утечку данных 3

## Вывод

текст