---
title: "Практическое задание №2"
author: "Журавлева Юлия БИСО-01-20"
format:   
  md:
    output-file: README.md
---

# Использование технологии Yandex DataLens для анализа данных сетевой активности

## Цель работы

1. Изучить возможности технологии Yandex DataLens для визуального анализа структурированных наборов данных
2. Получить навыки визуализации данных для последующего анализа с помощью сервисов Yandex Cloud
3. Получить навыки создания решений мониторинга/SIEM на базе облачных и открытых программных решений
4. Закрепить практические навыки использования SQL для анализа данных сетевой активности в сегментированной корпоративной сети

## Исходные данные

1. Ноутбук с ОС Windows 10
2. RStudio
3. Yandex Cloud
4. Yandex DataLens

## Задание

Используя сервис Yandex DataLens настроить доступ к результатам Yandex Query, полученным в ходе выполнения практической работы №1, и визуально представить результаты анализа данных.

### Поставленные задачи

1. Представить в виде круговой диаграммы соотношение внешнего и внутреннего сетевого трафика.
2. Представить в виде столбчатой диаграммы соотношение входящего и исходящего трафика из внутреннего сетвого сегмента.
3. Построить график активности (линейная диаграмма) объема трафика во времени.
4. Все построенные графики вывести в виде единого дашборда в Yandex DataLens.

## Ход работы

текст

## Анализ

текст

## Оценка результатов

текст

## Вывод

текст